# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fb0bb98760f858ea90d1caa6e17e1406b29b38862211311d1b5df66b88d2c8a7b9578149aca7ccffbf85570da712232d99cc16d4d71515c2f33412c576fcf5c

test:
  secret_key_base: f5c36dde932c0d61b25655826c781b5f9fb30aa832a4dede85d973fbd8a79e788414b2a4306987391dec441aee082e1e54bb687d37b7b64bd0e70122d3db939e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
